# Generated by Django 3.1 on 2022-10-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_used',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_credit',
            field=models.BooleanField(default=True),
        ),
    ]
